"""Scorers for the forgetting panels. GENERATED by scripts/make_kit_forgetting_assets.py: do not edit.

The functions below are source text copied from sdft/evaluate.py (answer extractors) and
sdft/ifeval_subset.py (a deliberately partial, self-contained IFEval-style checker: prompt-level
strict accuracy on the covered instruction types; comparable across our own runs, NOT with
published IFEval numbers). Standard library only.
"""
from __future__ import annotations

import re

_LETTER_PATTERNS = [
    re.compile(r"answer\s*(?:is|:)?\s*[\(\[]?\s*([A-D])\b", re.I),
    re.compile(r"correct answer is\s*[\(\[]?\s*([A-D])\b", re.I),
    re.compile(r"\b([A-D])\)"),
    re.compile(r"[\(\[]([A-D])[\)\]]"),
]

# Fallbacks, tried only when every pattern above fails, so nothing that already parsed changes.
# Unit F2 found the need for them: fine-tuning on the SDFT authors' science data, whose targets are
# "<answer>\nA\n</answer>", teaches the model to wrap its answer in angle brackets on EVERY
# multiple-choice task. It then writes "Answer: <C>" on physics and MMLU, which the patterns above
# cannot read. Scoring those as unparsed turned an 8-point drop into a 57-point one and would have
# been reported as catastrophic forgetting. The format drift is real and worth reporting; the loss
# of knowledge it implied was not.
_LETTER_FALLBACKS = [
    re.compile(r"answer\s*(?:is)?\s*[:\-]?\s*[<\(\[\{\*]+\s*([A-D])\b", re.I),
    re.compile(r"<answer>\s*[<\(\[]?\s*([A-D])\b", re.I),
]


def extract_letter(text: str) -> str | None:
    """Last confident letter mention wins; priority to explicit 'Answer:' forms, then the bracket
    fallbacks. Use extract_letter_strict to reproduce the pre-2026-09-04 behaviour."""
    for pat in _LETTER_PATTERNS:
        m = pat.findall(text)
        if m:
            return m[-1].upper()
    for pat in _LETTER_FALLBACKS:
        m = pat.findall(text)
        if m:
            return m[-1].upper()
    return None


def extract_letter_strict(text: str) -> str | None:
    """The extractor as it stood before unit F2 added the bracket fallbacks."""
    for pat in _LETTER_PATTERNS:
        m = pat.findall(text)
        if m:
            return m[-1].upper()
    return None


_NUM = re.compile(r"-?\d[\d,]*(?:\.\d+)?")


def extract_number(text: str) -> str | None:
    m = re.search(r"answer\s*(?:is|:)?\s*\$?\s*(-?\d[\d,]*(?:\.\d+)?)", text, re.I)
    if not m:
        nums = _NUM.findall(text)
        if not nums:
            return None
        m_val = nums[-1]
    else:
        m_val = m.group(1)
    v = m_val.replace(",", "")
    try:
        f = float(v)
        return str(int(f)) if f.is_integer() else str(f)
    except ValueError:
        return None


_WORD = re.compile(r"\b\w+\b")
_SENT = re.compile(r"[^.!?]+[.!?]*")


def _words(t: str) -> int:
    return len(_WORD.findall(t))


def _sentences(t: str) -> int:
    return len([s for s in _SENT.findall(t) if s.strip()])


def _rel(value: int, relation: str, target: int) -> bool:
    if relation == "at least":
        return value >= target
    if relation == "less than":
        return value < target
    raise ValueError(f"unsupported relation: {relation}")


def _count_kw(text: str, kw: str) -> int:
    return len(re.findall(rf"\b{re.escape(kw)}\b", text, re.I))


# Each checker: (response, kwargs) -> bool. Keys are IFEval instruction ids.
CHECKERS = {
 "punctuation:no_comma":
    lambda r, k: "," not in r,
 "change_case:english_lowercase":
    lambda r, k: r == r.lower(),
 "change_case:english_capital":
    lambda r, k: r == r.upper(),
 "keywords:existence":
    lambda r, k: all(_count_kw(r, w) > 0 for w in k["keywords"]),
 "keywords:forbidden_words":
    lambda r, k: all(_count_kw(r, w) == 0 for w in k["forbidden_words"]),
 "keywords:frequency":
    lambda r, k: _rel(_count_kw(r, k["keyword"]), k["relation"], k["frequency"]),
 "length_constraints:number_words":
    lambda r, k: _rel(_words(r), k["relation"], k["num_words"]),
 "length_constraints:number_sentences":
    lambda r, k: _rel(_sentences(r), k["relation"], k["num_sentences"]),
 "detectable_format:number_highlighted_sections":
    lambda r, k: len(re.findall(r"\*[^\*\n]+\*", r)) >= k["num_highlights"],
 "detectable_format:number_bullet_lists":
    lambda r, k: len(re.findall(r"^\s*\*[ \t]+\S", r, re.M)) == k["num_bullets"],
 "detectable_format:title":
    lambda r, k: bool(re.search(r"<<[^\n<>]+>>", r)),
 "detectable_content:number_placeholders":
    lambda r, k: len(re.findall(r"\[[^\[\]\n]*\]", r)) >= k["num_placeholders"],
 "detectable_content:postscript":
    lambda r, k: bool(re.search(rf"{re.escape(k['postscript_marker'])}", r, re.I)),
 "startend:end_checker":
    lambda r, k: r.strip().rstrip('"').strip().lower().endswith(k["end_phrase"].strip().lower()),
 "startend:quotation":
    lambda r, k: r.strip().startswith('"') and r.strip().endswith('"'),
}

SUPPORTED = frozenset(CHECKERS)


def follows_all(response: str, instruction_ids: list[str], kwargs_list: list[dict]) -> bool:
    """Prompt-level STRICT accuracy: every instruction on the prompt must be satisfied."""
    for iid, kw in zip(instruction_ids, kwargs_list):
        kw = {k: v for k, v in (kw or {}).items() if v is not None}
        if iid not in CHECKERS:
            raise KeyError(f"unsupported instruction id: {iid}")
        if not CHECKERS[iid](response, kw):
            return False
    return True


def score(panel: str, response: str, member: dict) -> dict:
    """One response against one panel member, exactly as continual/pilot_scoring.score_text does."""
    if panel == "math":
        prediction = extract_number(response)
        return {"correct": prediction == str(member["answer"]), "parsed": prediction is not None}
    if panel == "knowledge":
        prediction = extract_letter(response)
        return {"correct": prediction == member["answer"], "parsed": prediction is not None}
    if panel == "ifeval":
        parsed = bool(response.strip())
        meta = member["meta"]
        return {"correct": bool(parsed and follows_all(response, meta["instruction_id_list"], meta["kwargs"])),
                "parsed": parsed}
    raise KeyError("unknown panel: %s" % panel)
